# Generated by Django 5.0.4 on 2024-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="snp",
            name="alt_allele",
            field=models.CharField(
                choices=[("A", "A"), ("T", "T"), ("C", "C"), ("G", "G")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="snp",
            name="ref_allele",
            field=models.CharField(
                choices=[("A", "A"), ("T", "T"), ("C", "C"), ("G", "G")], max_length=1
            ),
        ),
    ]
